# Generated by Django 5.2.7 on 2025-10-28 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(choices=[('hanger', 'Hanger Station'), ('kita', 'Kita'), ('uber_eats', 'Uber Eats'), ('zomato', 'Zomato')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_platforms', to='core.company')),
            ],
            options={
                'verbose_name': 'منصة توصيل',
                'verbose_name_plural': 'منصات التوصيل',
                'unique_together': {('company', 'platform_name')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_order_id', models.CharField(max_length=100, unique=True)),
                ('delivery_address', models.TextField()),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='pending', max_length=20)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('driver_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('sales_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='pos.salesinvoice')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryplatform')),
            ],
            options={
                'verbose_name': 'طلب توصيل',
                'verbose_name_plural': 'طلبات التوصيل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryplatform')),
            ],
            options={
                'verbose_name': 'سجل التكامل',
                'verbose_name_plural': 'سجلات التكامل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='delivery.deliveryorder')),
            ],
            options={
                'verbose_name': 'تتبع التوصيل',
                'verbose_name_plural': 'تتبع التوصيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
