# Generated by Django 5.2.7 on 2025-10-25 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المصروفات')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الأرباح')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي الأرباح')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='core.company')),
            ],
            options={
                'verbose_name': 'تقرير مالي',
                'verbose_name_plural': 'التقارير المالية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('inventory', 'المخزون'), ('profit', 'الأرباح'), ('customers', 'العملاء'), ('suppliers', 'الموردين')], max_length=20)),
                ('metric_date', models.DateField(verbose_name='تاريخ المقياس')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('previous_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة التغيير %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='core.company')),
            ],
            options={
                'verbose_name': 'مقياس لوحة تحكم',
                'verbose_name_plural': 'مقاييس لوحة التحكم',
                'ordering': ['-metric_date'],
                'unique_together': {('company', 'metric_type', 'metric_date')},
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(verbose_name='تاريخ التقرير')),
                ('total_items', models.IntegerField(default=0, verbose_name='إجمالي المنتجات')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الكمية')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي القيمة')),
                ('low_stock_items', models.IntegerField(default=0, verbose_name='منتجات بمخزون منخفض')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reports', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='core.company')),
            ],
            options={
                'verbose_name': 'تقرير مخزون',
                'verbose_name_plural': 'تقارير المخزون',
                'ordering': ['-report_date'],
                'unique_together': {('company', 'branch', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('sales', 'تقرير المبيعات'), ('purchases', 'تقرير المشتريات'), ('inventory', 'تقرير المخزون'), ('financial', 'التقرير المالي'), ('production', 'تقرير الإنتاج'), ('customer', 'تقرير العملاء'), ('supplier', 'تقرير الموردين')], max_length=20)),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('data', models.JSONField(default=dict, verbose_name='بيانات التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='reports_rep_report__6e1fe1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(verbose_name='تاريخ التقرير')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_items_sold', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice_count', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reports', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='core.company')),
            ],
            options={
                'verbose_name': 'تقرير مبيعات',
                'verbose_name_plural': 'تقارير المبيعات',
                'ordering': ['-report_date'],
                'unique_together': {('company', 'branch', 'report_date')},
            },
        ),
    ]
