# Generated by Django 5.2.7 on 2025-10-25 08:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الوصفة')),
                ('output_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية المنتجة')),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, verbose_name='التعليمات')),
                ('production_time_minutes', models.IntegerField(default=0, verbose_name='وقت الإنتاج (دقيقة)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.product')),
            ],
            options={
                'verbose_name': 'وصفة',
                'verbose_name_plural': 'الوصفات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية المخططة')),
                ('produced_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية المنتجة')),
                ('planned_start_date', models.DateTimeField(verbose_name='تاريخ بداية مخطط')),
                ('planned_end_date', models.DateTimeField(verbose_name='تاريخ نهاية مخطط')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('planned', 'مخططة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.recipe')),
            ],
            options={
                'verbose_name': 'أمر إنتاج',
                'verbose_name_plural': 'أوامر الإنتاج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية')),
                ('is_main_ingredient', models.BooleanField(default=False, verbose_name='مكون رئيسي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='inventory.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='manufacturing.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
            options={
                'verbose_name': 'مكون وصفة',
                'verbose_name_plural': 'مكونات الوصفات',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية المخططة')),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الكمية المستهلكة')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.productionorder')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.recipeingredient')),
            ],
            options={
                'verbose_name': 'سطر أمر إنتاج',
                'verbose_name_plural': 'أسطر أوامر الإنتاج',
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', '-created_at'], name='manufacturi_status_361d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['branch', '-created_at'], name='manufacturi_branch__a9bfae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'product')},
        ),
    ]
